/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Miraculous.Empresa;

import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.table.TableModel;

/**
 *
 * @author Felipe
 */
public class jifAltDeletelEmpresa extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifConsulFunc
     */
    empresaDAO fd = new empresaDAO();
    Empresa p = new Empresa();
    EmpresaTableModel pt = new EmpresaTableModel(); 
    
     
    public jifAltDeletelEmpresa() {
        initComponents();
        setSize(1350,630);
        
      TabelaEmpresa.setModel(pt);
    }
        public void Tabela(String nome){
        
        DefaultTableModel modelo = (DefaultTableModel) TabelaEmpresa.getModel();
        modelo.setNumRows(0);
        empresaDAO ad = new empresaDAO();
        
        for(Empresa c : fd.listarTodos(nome)){
            
            modelo.addRow(new Object[]{
            c.getId_empresa(),
            c.getNome(),
            c.getRepresentante(),
            c.getTelefone(),
            c.getCnpj(),
            c.getEndereco(),
            c.getEmail()
            
        });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnExcluir = new javax.swing.JButton();
        btnAlt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaEmpresa = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Contato = new javax.swing.JTextField();
        txt_endereco = new javax.swing.JTextField();
        txt_Nome = new javax.swing.JTextField();
        txt_telefone = new javax.swing.JTextField();
        txtRep = new javax.swing.JTextField();
        btnList = new javax.swing.JButton();
        txtCnpj = new javax.swing.JFormattedTextField();
        txt_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(null);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(20, 540, 180, 30);

        btnAlt.setText("Alterar");
        btnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlt);
        btnAlt.setBounds(240, 540, 180, 30);

        TabelaEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TabelaEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaEmpresaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaEmpresa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(450, 210, 860, 370);

        jLabel3.setText("Empresa:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 220, 60, 30);

        jLabel6.setText("CNPJ:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 370, 50, 30);

        jLabel4.setText("Responsável: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 270, 68, 30);

        jLabel5.setText("Telefone:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 320, 60, 30);

        jLabel7.setText("Endereço:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 420, 60, 30);

        jLabel8.setText("Contato:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 470, 60, 30);
        getContentPane().add(txt_Contato);
        txt_Contato.setBounds(100, 470, 210, 30);
        getContentPane().add(txt_endereco);
        txt_endereco.setBounds(100, 420, 200, 30);
        getContentPane().add(txt_Nome);
        txt_Nome.setBounds(100, 220, 210, 30);
        getContentPane().add(txt_telefone);
        txt_telefone.setBounds(100, 320, 150, 30);
        getContentPane().add(txtRep);
        txtRep.setBounds(100, 270, 210, 30);

        btnList.setText("Listar Todos");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });
        getContentPane().add(btnList);
        btnList.setBounds(170, 90, 110, 30);

        txtCnpj.setEditable(false);
        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCnpjKeyPressed(evt);
            }
        });
        getContentPane().add(txtCnpj);
        txtCnpj.setBounds(100, 370, 182, 30);

        txt_id.setEditable(false);
        getContentPane().add(txt_id);
        txt_id.setBounds(100, 170, 210, 30);

        jLabel9.setText("ID:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 170, 34, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Icone.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 0, 1100, 640);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Liste todos os dados !");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 300, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:
        fd.conectar();
        pt.atualizar();
      List<Empresa> lista = fd.lista();
      pt.addLinha(lista);
    }//GEN-LAST:event_btnListActionPerformed

    private void txtCnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCnpjKeyPressed
        // TODO add your handling code here:

        
        
    }//GEN-LAST:event_txtCnpjKeyPressed

    private void TabelaEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaEmpresaMouseClicked
        // TODO add your handling code here:
        int i = TabelaEmpresa.getSelectedRow();
        TableModel model = TabelaEmpresa.getModel();
        txt_id.setText(model.getValueAt(i,0).toString());
        txt_Nome.setText(model.getValueAt(i,1).toString());
        txtRep.setText(model.getValueAt(i,2).toString());
        txt_telefone.setText(model.getValueAt(i,3).toString());
        txtCnpj.setText(model.getValueAt(i,4).toString());
        txt_endereco.setText(model.getValueAt(i,5).toString());
        txt_Contato.setText(model.getValueAt(i,6).toString());
        
    }//GEN-LAST:event_TabelaEmpresaMouseClicked

    private void btnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltActionPerformed
        // TODO add your handling code here:
       fd.conectar();
       String query = "UPDATE `tbempresa` SET `Nome`='"+txt_Nome.getText()+"',`Representante`='"+txtRep.getText()+"',`Telefone`='"+txt_telefone.getText()+"',`Cnpj`='"+txtCnpj.getText()+"',`Endereco`='"+txt_endereco.getText()+"',`Email`='"+txt_Contato.getText()+"' WHERE `id_empresa` = "+txt_id.getText();
       fd.executeSQlQuery(query,"Alterado");
        
      pt.atualizar();
      List<Empresa> lista = fd.lista();
      pt.addLinha(lista);
    }//GEN-LAST:event_btnAltActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
      fd.conectar();
      String query = "DELETE FROM `tbempresa` WHERE id_empresa ="+txt_id.getText();
      fd.executeSQlQuery(query, "Deletado");
      
      
      pt.atualizar();
      List<Empresa> lista = fd.lista();
      pt.addLinha(lista);
      
      
      
      
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaEmpresa;
    private javax.swing.JButton btnAlt;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JTextField txtRep;
    private javax.swing.JTextField txt_Contato;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_endereco;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
