/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Miraculous.Empresa;

/**
 *
 * @author Felipe
 */
public class jifCadEmpresa extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifCadEmpresa2
     */
         empresaDAO ed = new empresaDAO();
         Empresa emp = new Empresa();
         
         
         
    public jifCadEmpresa() {
        initComponents();
             ed.conectar();
             setSize(932,721);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        txt_endereco = new javax.swing.JTextField();
        txt_Nome = new javax.swing.JTextField();
        txt_telefone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtRepres = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JFormattedTextField();
        txtEmail2 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Empresa");
        getContentPane().setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/LOGO.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(360, 0, 570, 690);

        jLabel1.setText("Empresa:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 100, 90, 40);

        jLabel6.setText("CNPJ:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 370, 60, 30);

        jLabel2.setText("Representante:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 160, 90, 30);

        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 320, 80, 30);

        jLabel7.setText("Endereço:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 270, 70, 30);

        Email.setText("Email :");
        getContentPane().add(Email);
        Email.setBounds(80, 210, 80, 30);
        getContentPane().add(txt_endereco);
        txt_endereco.setBounds(160, 270, 170, 30);
        getContentPane().add(txt_Nome);
        txt_Nome.setBounds(160, 100, 140, 30);
        getContentPane().add(txt_telefone);
        txt_telefone.setBounds(160, 320, 130, 30);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 480, 120, 40);

        txtRepres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepresActionPerformed(evt);
            }
        });
        getContentPane().add(txtRepres);
        txtRepres.setBounds(160, 160, 144, 30);

        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCnpjKeyPressed(evt);
            }
        });
        getContentPane().add(txtCnpj);
        txtCnpj.setBounds(160, 370, 182, 30);
        getContentPane().add(txtEmail2);
        txtEmail2.setBounds(160, 210, 160, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
           
            emp.setNome(txt_Nome.getText());
            emp.setRepresentante(txtRepres.getText());
            emp.setTelefone(Integer.parseInt(txt_telefone.getText()));
            emp.setCnpj(txtCnpj.getText());
            emp.setEndereco(txt_endereco.getText());
            emp.setEmail(txtEmail2.getText()); 
        
            
            System.out.println(emp.getNome()+"\n"+emp.getRepresentante()+"\n"+emp.getCnpj()+"\n"+emp.getTelefone()+"\n"+emp.getEndereco()+"\n"+emp.getEmail()+"\n");
            ed.conectar();
            ed.inserirE(emp.getId_empresa(),emp.getNome(),emp.getRepresentante(),emp.getTelefone(),emp.getCnpj(),emp.getEndereco(),emp.getEmail());
            
            txt_Nome.setText("");
            txtRepres.setText("");
            txt_telefone.setText("");
            txtCnpj.setText("");
            txt_endereco.setText("");
            txtEmail2.setText("");
}
        catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("erro: " + e);
        }        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtRepresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepresActionPerformed

    private void txtCnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCnpjKeyPressed
        // TODO add your handling code here:

       
    }//GEN-LAST:event_txtCnpjKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtRepres;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_endereco;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
