/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Miraculous.Projeto;

import Miraculous.Projeto.Projeto;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author felipe
 */
public class jifDeletaProj extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifDeletaProj
     */
    ProjetoDAO fd = new ProjetoDAO();
    Projeto p = new Projeto();
    ProjetoTableModel pt = new ProjetoTableModel();
    
    
    public jifDeletaProj() {
        initComponents();
        fd.conectar();
        setSize(900,643);
        tabela.setModel(pt);
        
        
        
    }
    private final String user="root";
   private final String passaword="";
   private final String url="jdbc:mysql://localhost:3306/empresa";
   Connection con;
   private Statement st;
   private ResultSet rs;
   
    public List<Projeto> listarTodos(String id_proj){
    
    List<Projeto> listaTd = new ArrayList<Projeto>();
    
   
    
        try {
            
            String sql = "SELECT * FROM projeto WHERE id_proj LIKE ?";
            st = con.prepareStatement(sql);
            rs = st.executeQuery(sql);
            
            while(rs.next()){
            Projeto p = new Projeto();
            p.setId_Proj(rs.getInt("id_proj")); 
            p.setNomeE(rs.getString("NomeE")); 
            p.setNomeP(rs.getString("NomeP")); 
            p.setCnpj(rs.getString("Cnpj")); 
            p.setDataInicio(rs.getString("dataInicio")); 
            p.setDataFim(rs.getString("DataFim")); 
            listaTd.add (p);
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    return  listaTd;
    
    }
    
    
    
    public void Tabela(String id_proj){
        
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        ProjetoDAO ad = new ProjetoDAO();
        
        for(Projeto c : ad.listarTodos(id_proj)){
            
            modelo.addRow(new Object[]{
            c.getId_Proj(),
            c.getNomeE(),
            c.getNomeP(),
            c.getCnpj(),
            c.getDataInicio(),
            c.getDataFim()
            
        });
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bntDeleta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDeleta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Exclusão de projetos");
        getContentPane().setLayout(null);

        bntDeleta.setText("Deletar");
        bntDeleta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bntDeleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDeletaActionPerformed(evt);
            }
        });
        getContentPane().add(bntDeleta);
        bntDeleta.setBounds(330, 160, 97, 30);

        jLabel1.setText("\"ID\" e nome do projeto que sera deletado !!!");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 130, 270, 30);

        txtDeleta.setEditable(false);
        txtDeleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeletaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDeleta);
        txtDeleta.setBounds(0, 170, 80, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Listar Todos");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 220, 110, 30);

        jLabel3.setText("Dados da Pesquisa:  ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 260, 140, 20);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabela);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(0, 290, 730, 320);

        txtNome.setEditable(false);
        getContentPane().add(txtNome);
        txtNome.setBounds(0, 220, 290, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Icone.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 0, 1145, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntDeletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDeletaActionPerformed
        // TODO add your handling code here:
      fd.conectar();
      String query = "DELETE FROM `projeto` WHERE id_proj ="+txtDeleta.getText();
      fd.executeSQlQuery(query, "Deletado");
      
      
      pt.atualizar();
      List<Projeto> lista = fd.lista();
      pt.addLinha(lista);
        
    }//GEN-LAST:event_bntDeletaActionPerformed

    private void txtDeletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeletaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtDeletaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        pt.atualizar();
        List<Projeto> lista = fd.lista();
        pt.addLinha(lista);
        
       /* */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        int i = tabela.getSelectedRow();
        TableModel model = tabela.getModel();
        txtDeleta.setText(model.getValueAt(i,0).toString());
        txtNome.setText(model.getValueAt(i,2).toString());

    }//GEN-LAST:event_tabelaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntDeleta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtDeleta;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
