package Miraculous;


import Miraculous.Empresa.jifAltDeletelEmpresa;
import Miraculous.Empresa.jifCadEmpresa;
import Miraculous.Funcionario.jifCadfunc;
import Miraculous.Funcionario.jifAltDeleteFunc;
import Miraculous.Funcionario.jifConsultaFuncionario;
import Miraculous.Projeto.jifCadProjeto;
import Miraculous.Projeto.jifDeletaProj;
import Miraculous.Projeto.jifConsuProj;
import Miraculous.Projeto.jifAltProj;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Stavo
 * @author Felipe
 */
public class frm_Principal extends javax.swing.JFrame {

    public frm_Principal() {
        initComponents();
        setIcon();
        LoginN n = new LoginN();
        PrincipalDAO fd = new PrincipalDAO();
       
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jdpPrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblHora = new javax.swing.JLabel();
        btnLogoff = new javax.swing.JButton();
        lblData = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFunc = new javax.swing.JMenu();
        jMenuCadFunc = new javax.swing.JMenuItem();
        ConsuFuncionario = new javax.swing.JMenuItem();
        jMenuConsFunc = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuCadEmpresa = new javax.swing.JMenuItem();
        MenuConsultaE = new javax.swing.JMenuItem();
        MenuProj = new javax.swing.JMenu();
        jMenuCadProj = new javax.swing.JMenuItem();
        jConsuProj = new javax.swing.JMenuItem();
        MenuAltProj = new javax.swing.JMenuItem();
        ExProjMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        SobreM = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Miraculous");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jdpPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        jdpPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jdpPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1146, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );

        lblHora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnLogoff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogoff.setText("Logoff");
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoffActionPerformed(evt);
            }
        });

        lblData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jMenuFunc.setText("Funcionario");
        jMenuFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFuncActionPerformed(evt);
            }
        });

        jMenuCadFunc.setText("Cadastro Funcionario");
        jMenuCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadFuncActionPerformed(evt);
            }
        });
        jMenuFunc.add(jMenuCadFunc);

        ConsuFuncionario.setText("Consulta de Funcionarios");
        ConsuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsuFuncionarioActionPerformed(evt);
            }
        });
        jMenuFunc.add(ConsuFuncionario);

        jMenuConsFunc.setText("Manipulação de Funcionarios");
        jMenuConsFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsFuncActionPerformed(evt);
            }
        });
        jMenuFunc.add(jMenuConsFunc);

        jMenuBar1.add(jMenuFunc);

        jMenu3.setText("Empresa");

        MenuCadEmpresa.setText("Cadastro de Empresa");
        MenuCadEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadEmpresaActionPerformed(evt);
            }
        });
        jMenu3.add(MenuCadEmpresa);

        MenuConsultaE.setText("Manipulação Empresa");
        MenuConsultaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultaEActionPerformed(evt);
            }
        });
        jMenu3.add(MenuConsultaE);

        jMenuBar1.add(jMenu3);

        MenuProj.setText("Projetos");
        MenuProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProjActionPerformed(evt);
            }
        });

        jMenuCadProj.setText("Cadastro de Projetos");
        jMenuCadProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadProjActionPerformed(evt);
            }
        });
        MenuProj.add(jMenuCadProj);

        jConsuProj.setText("Consulta de Projetos");
        jConsuProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsuProjActionPerformed(evt);
            }
        });
        MenuProj.add(jConsuProj);

        MenuAltProj.setText("Alteração de Projetos");
        MenuAltProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAltProjActionPerformed(evt);
            }
        });
        MenuProj.add(MenuAltProj);

        ExProjMenu.setText("Exclusão de Projetos");
        ExProjMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExProjMenuActionPerformed(evt);
            }
        });
        MenuProj.add(ExProjMenu);

        jMenuBar1.add(MenuProj);

        jMenu2.setText("Sobre");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        SobreM.setText("Sobre Miraculous ");
        SobreM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreMActionPerformed(evt);
            }
        });
        jMenu2.add(SobreM);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdpPrincipal)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(btnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpPrincipal)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnLogoff)
                                .addComponent(btnSair))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadFuncActionPerformed
        jifCadfunc obj=new jifCadfunc();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuCadFuncActionPerformed
  
   
    
    private void jMenuCadProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadProjActionPerformed
        // TODO add your handling code here:
        Component obj=new jifCadProjeto();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuCadProjActionPerformed

    private void jMenuConsFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsFuncActionPerformed
        Component obj=new jifAltDeleteFunc();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuConsFuncActionPerformed

    private void MenuProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProjActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MenuProjActionPerformed

    private void jConsuProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsuProjActionPerformed
        // TODO add your handling code here:
        Component obj=new jifConsuProj();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jConsuProjActionPerformed

    private void jMenuFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuFuncActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void SobreMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreMActionPerformed
        // TODO add your handling code here:
         Component obj=new Sobre();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_SobreMActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
        //maximização da tela ao iniciar
        setExtendedState(MAXIMIZED_BOTH);
        //
        
        // Pegando data do sistema
        Date ds = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        lblData.setText(formato.format(ds));
        
        // hora do sistema
        Timer t = new Timer(1000,new hora());
        t.start();
        //
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoffActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginN pr = new LoginN();
        pr.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_btnLogoffActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
         System.exit(0);
         
         
    }//GEN-LAST:event_btnSairActionPerformed

    private void ExProjMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExProjMenuActionPerformed
        // TODO add your handling code here:
        Component obj=new jifDeletaProj();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_ExProjMenuActionPerformed

    private void MenuAltProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAltProjActionPerformed
        // TODO add your handling code here:
        Component obj=new jifAltProj();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_MenuAltProjActionPerformed

    private void MenuConsultaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultaEActionPerformed
  // TODO add your handling code here:
        Component obj=new jifAltDeletelEmpresa();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_MenuConsultaEActionPerformed

    private void MenuCadEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadEmpresaActionPerformed
        // TODO add your handling code here:
        Component obj= new jifCadEmpresa();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_MenuCadEmpresaActionPerformed

    private void ConsuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsuFuncionarioActionPerformed
        // TODO add your handling code here:
        Component obj = new jifConsultaFuncionario();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_ConsuFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConsuFuncionario;
    private javax.swing.JMenuItem ExProjMenu;
    private javax.swing.JMenuItem MenuAltProj;
    private javax.swing.JMenuItem MenuCadEmpresa;
    private javax.swing.JMenuItem MenuConsultaE;
    private javax.swing.JMenu MenuProj;
    private javax.swing.JMenuItem SobreM;
    private javax.swing.JButton btnLogoff;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenuItem jConsuProj;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadFunc;
    private javax.swing.JMenuItem jMenuCadProj;
    private javax.swing.JMenuItem jMenuConsFunc;
    private javax.swing.JMenu jMenuFunc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    // End of variables declaration//GEN-END:variables


//icone da classe principal
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icone.png")));
    }
    
    //função para pegar hora do sistema
    class hora implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            Calendar Cal = Calendar.getInstance();
            lblHora.setText(String.format("%1$tH:%1$tM:%1$tS",Cal));
        }
    }
}
