package Miraculous.Funcionario;

import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Stavo
 */
public class jifAltDeleteFunc extends javax.swing.JInternalFrame {
    
    
    funcDAO fd = new funcDAO ();
    FuncionarioTableModel pt = new FuncionarioTableModel();

    public jifAltDeleteFunc() {
        initComponents();
        //tamanho da tela
        setSize(1112,640);
        
      Tabela.setModel(pt);
      fd.conectar();
      //listando ao abrir a tela
      pt.atualizar();
      List<CadFunc> lista = fd.lista();
      pt.addLinha(lista);
    }
            public void Tabela(String nome){
        
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        modelo.setNumRows(0);
        funcDAO ad = new funcDAO();
        
        for(CadFunc c : fd.listarTodos(nome)){
            
            modelo.addRow(new Object[]{
            c.getId_func(),
            c.getNome(),
            c.getCpf(),
            c.getDtn(),
            c.getCargo(),
            c.getSalario(),
            c.getProjeto()
            
        });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupConF = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnAlt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtSal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtProj = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JFormattedTextField();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta Funcionario");
        getContentPane().setLayout(null);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(480, 10, 610, 590);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(40, 440, 180, 30);

        btnAlt.setText("Alterar");
        btnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlt);
        btnAlt.setBounds(250, 440, 180, 30);

        jLabel2.setText("Nome: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 60, 40);

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(70, 110, 270, 40);

        txtCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCargoKeyPressed(evt);
            }
        });
        getContentPane().add(txtCargo);
        txtCargo.setBounds(80, 380, 210, 30);

        jLabel3.setText("CPF: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 50, 40);

        txtCPF.setEditable(false);
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCPFKeyPressed(evt);
            }
        });
        getContentPane().add(txtCPF);
        txtCPF.setBounds(70, 170, 290, 30);

        txtSal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSalKeyPressed(evt);
            }
        });
        getContentPane().add(txtSal);
        txtSal.setBounds(80, 340, 140, 30);

        jLabel5.setText("Data de Nascimento: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 220, 110, 40);

        jLabel7.setText("Projeto: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 280, 70, 40);

        txtProj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProjKeyPressed(evt);
            }
        });
        getContentPane().add(txtProj);
        txtProj.setBounds(80, 290, 240, 30);

        jLabel6.setText("Salario: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 330, 60, 40);

        jLabel8.setText("Cargo: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 370, 60, 40);

        try {
            txtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNascimentoActionPerformed(evt);
            }
        });
        txtNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNascimentoKeyPressed(evt);
            }
        });
        getContentPane().add(txtNascimento);
        txtNascimento.setBounds(130, 230, 88, 30);

        txtId.setEditable(false);
        getContentPane().add(txtId);
        txtId.setBounds(70, 60, 40, 30);

        jLabel1.setText("ID: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 60, 30, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Icone.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(75, 0, 1520, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode () == KeyEvent.VK_ENTER){
            txtCPF.grabFocus();
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCargoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode () == KeyEvent.VK_ENTER){
            txtSal.grabFocus();
        }
    }//GEN-LAST:event_txtCargoKeyPressed

    private void txtCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCPFKeyPressed

    private void txtSalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode () == KeyEvent.VK_ENTER){
            txtProj.grabFocus();
        }
    }//GEN-LAST:event_txtSalKeyPressed

    private void txtProjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProjKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtProjKeyPressed

    private void txtNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNascimentoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNascimentoActionPerformed

    private void txtNascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNascimentoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNascimentoKeyPressed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        // TODO add your handling code here:
        int i = Tabela.getSelectedRow();
        TableModel model = Tabela.getModel();
        txtId.setText(model.getValueAt(i,0).toString());
        txtNome.setText(model.getValueAt(i,1).toString());
        txtCPF.setText(model.getValueAt(i,2).toString());
        txtNascimento.setText(model.getValueAt(i,3).toString());
        txtProj.setText(model.getValueAt(i,6).toString());
        txtSal.setText(model.getValueAt(i,5).toString());
        txtCargo.setText(model.getValueAt(i,4).toString());
    }//GEN-LAST:event_TabelaMouseClicked

    private void btnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltActionPerformed
        // TODO add your handling code here:
       fd.conectar();
       String query = "UPDATE `funcionario` SET `nome`='"+txtNome.getText()+"',`cpf`='"+txtCPF.getText()+"',`dtn`='"+txtNascimento.getText()+"',`cargo`='"+txtCargo.getText()+"',`salario`="+txtSal.getText()+",`projeto`='"+txtProj.getText()+"' WHERE id_func = "+txtId.getText();
       fd.executeSQlQuery(query,"Alterado");
        
      pt.atualizar();
      List<CadFunc> lista = fd.lista();
      pt.addLinha(lista);
    }//GEN-LAST:event_btnAltActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
      fd.conectar();
      String query = "DELETE FROM `funcionario` WHERE id_func ="+txtId.getText();
      fd.executeSQlQuery(query, "Deletado");
      
      
      pt.atualizar();
      List<CadFunc> lista = fd.lista();
      pt.addLinha(lista);
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupConF;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btnAlt;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtId;
    private javax.swing.JFormattedTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtProj;
    private javax.swing.JTextField txtSal;
    // End of variables declaration//GEN-END:variables
}
