/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Miraculous.Funcionario;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class jifConsultaFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifCadFuncionario
     */
    CadFunc f = new CadFunc ();
    funcDAO fd = new funcDAO();
    
    public jifConsultaFuncionario() {
        initComponents();
        fd.conectar();
        setSize(900,550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        rBtnId = new javax.swing.JRadioButton();
        rBtnCpf = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(null);

        jLabel1.setText("Escolha o \"ID\" ou Cpf para busca");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 32, 180, 30);

        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaKeyPressed(evt);
            }
        });
        getContentPane().add(txtBusca);
        txtBusca.setBounds(10, 140, 181, 30);

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane2.setViewportView(txtArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 209, 450, 298);

        buttonGroup1.add(rBtnId);
        rBtnId.setText("ID");
        getContentPane().add(rBtnId);
        rBtnId.setBounds(120, 70, 60, 23);

        buttonGroup1.add(rBtnCpf);
        rBtnCpf.setText("Cpf");
        getContentPane().add(rBtnCpf);
        rBtnCpf.setBounds(30, 70, 60, 23);

        jLabel2.setText("Digite o Campo de busca :  ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 101, 150, 30);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(210, 140, 84, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Icone.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(215, 0, 670, 518);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
       
        if(rBtnCpf.isSelected()){
        String Cpf=(txtBusca.getText());
        txtArea.setText(fd.ConsultaCpf(Cpf));
        }else if(rBtnId.isSelected()){
        int id_func=Integer.parseInt(txtBusca.getText());
        txtArea.setText(fd.ConsultaId(id_func));
        }
       
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode () == KeyEvent.VK_ENTER){
           btnBuscar.doClick();
       }
    }//GEN-LAST:event_txtBuscaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rBtnCpf;
    private javax.swing.JRadioButton rBtnId;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
